<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
  
  <xacro:property name="mm2m" value="0.001"/>

  <xacro:property name="chassis_length" value="${700*mm2m}"/>
  <xacro:property name="chassis_width" value="${550*mm2m}"/>
  <xacro:property name="chassis_height" value="${175*mm2m}"/>

  <xacro:property name="drive_wheel_radius" value="${80*mm2m}"/>
  <xacro:property name="drive_wheel_width" value="${40*mm2m}"/>

  <xacro:property name="drive_wheel_axis_offset" value="${50*mm2m}"/>
  <xacro:property name="track_width" value="${chassis_width - drive_wheel_width}"/>

  <xacro:property name="caster_wheel_radius" value="${20*mm2m}"/>
  <xacro:property name="caster_wheel_width" value="${15*mm2m}"/>


  <xacro:property name="lidar_radius" value="${30*mm2m}"/>
  <xacro:property name="lidar_width" value="${20*mm2m}"/>

</robot>