<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:lidar 
    name="lidar" 
    parent="chassis_link"
    xyz="0 0 ${chassis_height + lidar_width/2 + 5*mm2m}" 
    rpy="0 0 0"
    radius="${lidar_radius}" 
    width="${lidar_width}" 
    m="0.1" 
    material_name="black" 
  />
  
</robot>