<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <joint name="imu_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="imu_link" />
    <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
  </joint>

  <link name="imu_link">
    <visual>
      <geometry>
        <box size="${imu_length} ${imu_width} ${imu_height}"/>
      </geometry>
      <material name="black"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>

    <collision>
      <geometry>
        <box size="${imu_length} ${imu_width} ${imu_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>

    <xacro:inertia 
      shape="box" 
      xyz="0 0 0" 
      rpy="0 0 0" 
      l="${imu_length}" 
      w="${imu_width}" 
      h="${imu_height}" 
      m="0.02"
    />
  </link>
  
</robot>