<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">  

  <link name="base_link"/>

  <!-- Base Frame -->
  <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link" />
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="chassis_link">
    <visual>
      <geometry>
        <mesh filename="file://$(find twr_description)/mesh/twr_base.dae"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>

    <collision>
      <geometry>
        <mesh filename="file://$(find twr_description)/mesh/twr_base.dae"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>

    <xacro:inertia 
      shape="box" 
      xyz="0 0 ${chassis_height/2}" 
      rpy="0 0 0" 
      l="${chassis_length}" 
      w="${chassis_width}" 
      h="${chassis_height}" 
      m="1"
    />

  </link>

  <!-- Base Footprint -->
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint" />
    <origin xyz="0 0 ${-drive_wheel_radius + drive_wheel_axis_offset}" rpy="0 0 0"/>
  </joint>

  <link name="base_footprint"/>

</robot>