<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <xacro:wheel 
    name="left_wheel" 
    type="drive"
    parent="base_link" 
    xyz="0 ${track_width/2} ${drive_wheel_axis_offset}" 
    rpy="${-pi/2} 0 0" 
    radius="${drive_wheel_radius}" 
    width="${drive_wheel_width}" 
    m="0.2" 
    xyz_axis="0 0 1" 
    material_name="orange" 
  />

  <xacro:wheel 
    name="right_wheel"
    type="drive"
    parent="base_link" 
    xyz="0 ${-track_width/2} ${drive_wheel_axis_offset}" 
    rpy="${-pi/2} 0 0" 
    radius="${drive_wheel_radius}" 
    width="${drive_wheel_width}" 
    m="0.2" 
    xyz_axis="0 0 1" 
    material_name="orange" 
  />

</robot>