controller_server:
  ros__parameters:
    controller_frequency: 20.0
    costmap_update_timeout: 0.30
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]
    use_realtime_priority: false
    enable_stamped_cmd_vel: true

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 15.0

    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.03 # [m]
      yaw_goal_tolerance: 0.0175 # [rad] ~1 degree

    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      motion_model: "DiffDrive"
      
      # 
      # prediction horizon = time_steps * model_dt 
      time_steps: 60
      model_dt: 0.05
      batch_size: 2000
      prune_distance: 1.0
      vx_max: 1.5
      vx_min: -0.5 # 0.0 - to prevent reverse motion
      wz_max: 2.0
      ax_max: 3.0
      ax_min: -3.0
      az_max: 3.5
      vx_std: 0.2
      wz_std: 0.4
      transform_tolerance: 0.1

      # temperature: exploration and exploitation balance (lambda)
      # High lambda - more exploration
      # Low lambda - more exploitation
      temperature: 0.2
      gamma: 0.015
      iteration_count: 1
      visualize: true
      regenerate_noises: false

      TrajectoryVisualizer:
        trajectory_step: 5
        time_step: 3

      critics: [
        "ConstraintCritic", 
        "CostCritic", 
        "GoalCritic", "GoalAngleCritic", 
        "PathAlignCritic", "PathFollowCritic","PathAngleCritic",
        "PreferForwardCritic"
      ]

      # A higher weight makes the critic more influential

      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
      
      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 1.0
        near_collision_cost: 253
        critical_cost: 300.0
        consider_footprint: false
        collision_cost: 1000000.0
        near_goal_distance: 1.0
        trajectory_point_step: 2
      
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 0.5
      
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 0.1
      
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 15.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 4
        threshold_to_consider: 0.1
        offset_from_furthest: 20
        use_path_orientations: false
      
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        offset_from_furthest: 5
        threshold_to_consider: 0.1

      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0
        offset_from_furthest: 4
        threshold_to_consider: 0.1
        max_angle_to_furthest: 1.0
        mode: 0

      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 0.1