site_name:  Two-Wheeled Robot
site_url: https://ajedancov.github.io/twr/
repo_url: https://github.com/AJedancov/twr


theme:
  name: material
  custom_dir: overrides
  font:
    text: Inter
    code: Oxygen Mono

  features:
  - navigation.path
  - navigation.tabs
  - navigation.indexes
  - navigation.top

  - content.code.copy
  - content.code.annotate

  - toc.follow

  palette:
    primary: white

  favicon: assets/twr_logo.png
  logo: assets/twr_logo.png
  
  icon:
    repo: fontawesome/brands/github
    annotation: material/help-circle


plugins:
  - search
  - glightbox
  - social:
      cards_layout_options:
        background_color: "#ededf3"


markdown_extensions:
  - admonition
  - tables
  - toc # Table of Contents

  - attr_list
  - md_in_html

  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  # Path relative to custom_dir (overrides/):
  - assets/stylesheets/extra.css
  - assets/stylesheets/buttons.css

copyright: Copyright &copy; 2025 Andrei Jedancov

# Terminate the build on warnings
strict: true

validation:
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn
  nav:
    omitted_files: warn
    absolute_links: warn

INHERIT: nav.yml
