controller_manager:
  ros__parameters:
    update_rate: 1000 #Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController

    odom_frame_id: odom
    base_frame_id: base_footprint

    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.222
    wheel_radius: 0.05

    use_stamped_vel: false