site_name:  Two-Wheeled Robot
site_url: https://ajedancov.github.io/twr/
repo_url: https://github.com/AJedancov/twr


theme:
  name: material
  font:
    text: Inter
    code: Oxygen Mono

  features:
  - navigation.path
  - navigation.tabs
  - navigation.indexes
  - navigation.top

  - content.code.copy
  - content.code.annotate

  - toc.follow

  palette:
    primary: white

  favicon: _assets/twr_logo.png
  logo: _assets/twr_logo.png
  
  icon:
    repo: fontawesome/brands/github
    annotation: material/help-circle


plugins:
  - social:
      cards_layout_options:
        background_color: "#ededf3"


markdown_extensions:
  - admonition
  - tables
  - toc # Table of Contents

  - attr_list
  - md_in_html

  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true


extra_css:
  - _stylesheets/extra.css


copyright: Copyright &copy; 2025 Andrei Jedancov


nav:
  - Home:
    - index.md

  - Getting started:
    - Installation:
      - getting_started/installation/index.md
      - Locally: getting_started/installation/locally.md
      - Docker: getting_started/installation/docker.md
    - Usage: getting_started/usage.md

  - Documentation:
    - TWR:
      - documentation/twr/index.md
      - Sensors:
        - LiDAR: documentation/twr/sensors/lidar.md 
        - IMU: documentation/twr/sensors/imu.md
        - Encoders: documentation/twr/sensors/encoders.md
    - Simulation:
      - documentation/simulation/index.md
    - Software:
      - documentation/software/index.md
      - Project structure:
        - scripts: documentation/software/project_structure/scripts.md
        - twr_bringup: documentation/software/project_structure/twr_bringup.md
        - twr_control: documentation/software/project_structure/twr_control.md
        - twr_description: documentation/software/project_structure/twr_description.md
        - twr_navigation: documentation/software/project_structure/twr_navigation.md
        - twr_sim: documentation/software/project_structure/twr_sim.md
      # - documentation/software/launch_file_structure.md
      - documentation/software/launch_process.md

  - Tutorials:
    - tutorials/index.md