<?xml version="1.0"?>
<robot name="twr" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Include files -->
    <xacro:include filename="_inertia.macro.xacro"/>
    <xacro:include filename="_colors.xacro"/>
    <xacro:include filename="ros2_control.xacro"/>
    <xacro:include filename="gz.xacro"/>
    <xacro:include filename="wheel.macro.xacro"/>

    <xacro:property name="mm2m" value="0.001"/>

    <xacro:property name="base_length" value="${200*mm2m}"/>
    <xacro:property name="base_width" value="${200*mm2m}"/>
    <xacro:property name="base_height" value="${40*mm2m}"/>

    <xacro:property name="wheel_radius" value="${50*mm2m}"/>
    <xacro:property name="wheel_width" value="${20*mm2m}"/>

    <xacro:property name="caster_wheel_radius" value="${10*mm2m}"/>

    <!-- ============= -->
    <!-- === WORLD === -->
    <!-- ============= -->
    <link name="odom"/>


    <!-- ============ -->
    <!-- === BASE === -->
    <!-- ============ -->
    <joint name="base_joint" type="fixed">
        <parent link="odom"/>
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius+0.001}" rpy="0 0 0"/>
    </joint>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="white"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </visual>

        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>

        <xacro:inertia shape="box" xyz="0 0 0" rpy="0 0 0" l="${base_length}" w="${base_width}" h="${base_height}" m="1"/>

    </link>

    <!-- ============== -->
    <!-- === WHEELS === -->
    <!-- ============== -->
    <xacro:wheel 
        name="left_wheel" 
        type="standart"
        parent="base_link" 
        xyz="0 ${base_width/2 + wheel_width/2 + 0.01} 0" 
        rpy="-${pi/2} 0 0" 
        radius="${wheel_radius}" 
        width="${wheel_width}" 
        m="0.2" 
        xyz_axis="0 0 1" 
        material_name="orange" 
    />
    
    <xacro:wheel 
        name="right_wheel"
        type="standart"
        parent="base_link" 
        xyz="0 -${base_width/2 + wheel_width/2 + 0.01} 0" 
        rpy="-${pi/2} 0 0" 
        radius="${wheel_radius}" 
        width="${wheel_width}" 
        m="0.2" 
        xyz_axis="0 0 1" 
        material_name="orange" 
    />

    <xacro:wheel 
        name="caster_front_wheel" 
        type="caster"
        parent="base_link" 
        xyz="${base_length/2-caster_wheel_radius} 0 -${wheel_radius-caster_wheel_radius-1*mm2m}" 
        rpy="0 0 0" 
        radius="${caster_wheel_radius}" 
        width="${caster_wheel_radius}" 
        m="0.01" 
        xyz_axis="0 0 0" 
        material_name="white" 
    />

    <xacro:wheel 
        name="caster_back_wheel" 
        type="caster"
        parent="base_link" 
        xyz="-${base_length/2-caster_wheel_radius} 0 -${wheel_radius-caster_wheel_radius-1*mm2m}" 
        rpy="0 0 0" 
        radius="${caster_wheel_radius}" 
        width="${caster_wheel_radius}" 
        m="0.01" 
        xyz_axis="0 0 0" 
        material_name="white" 
    />

</robot>
