name: docs-ci 

on:
  push:
    branches:
      - jazzy
    paths:
      - twr_docs/**
      - .github/workflows/docs-ci.yml

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v6
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - working-directory: twr_docs
        run: pip3 install -r requirements.txt
      - working-directory: twr_docs
        run: zensical build --clean
      - uses: actions/upload-pages-artifact@v5
        with:
          path: twr_docs/site
      - uses: actions/deploy-pages@v5
        id: deployment
